### PR TITLE
Add publish snapshots to maven via GHA

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description
- Added publish snapshots to maven via GHA

### Issues Resolved
https://github.com/opensearch-project/observability/issues/1414

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rupal-bq** [comment]
Local test output 
```
maharup@b0f1d879dff7 observability % ./gradlew publishPluginZipPublicationToSnapshotsRepository
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 13.2 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
  Random Testing Seed   : 1044FD700D3634BE
  In FIPS 140 mode      : false
=======================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
10 actionable tasks: 3 executed, 7 up-to-date
maharup@b0f1d879dff7 observability % find snapshots | sort
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/observability
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.pom
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.pom.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.pom.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.pom.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.pom.sha512
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.zip
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.zip.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.zip.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.zip.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202117-1.zip.sha512
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.pom
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.pom.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.pom.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.pom.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.pom.sha512
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.zip
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.zip.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.zip.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.zip.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230220.202712-2.zip.sha512
snapshots/org/opensearch/plugin/observability/maven-metadata.xml
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha512
maharup@b0f1d879dff7 observability % 

```

**Comment by gaiksaya** [comment]
Hi @rupal-bq, shouldn't the name be `opensearch-observability`?
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-observability/

**Comment by rupal-bq** [comment]
> Hi @rupal-bq, shouldn't the name be `opensearch-observability`? https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-observability/

Thanks for noticing. Output after adding rootProject.name = 'opensearch-observability'

```
maharup@b0f1d879dff7 observability % ./gradlew publishPluginZipPublicationToSnapshotsRepository
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 13.2 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
  Random Testing Seed   : 32B6B964AEB93F20
  In FIPS 140 mode      : false
=======================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
10 actionable tasks: 3 executed, 7 up-to-date
maharup@b0f1d879dff7 observability % find snapshots | sort                                     
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/observability
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.sha512
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.md5
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.sha1
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.sha256
snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.sha512
snapshots/org/opensearch/plugin/observability/maven-metadata.xml
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha512
snapshots/org/opensearch/plugin/opensearch-observability
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.sha512
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.sha512
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.sha512
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.sha512
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha512
maharup@b0f1d879dff7 observability %

**Review by ps48 — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]

**Comment by gaiksaya** [comment]
> > Hi @rupal-bq, shouldn't the name be `opensearch-observability`? https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-observability/
> 
> Thanks for noticing. Output after adding rootProject.name = 'opensearch-observability'
> 
> ```
> maharup@b0f1d879dff7 observability % ./gradlew publishPluginZipPublicationToSnapshotsRepository
> =======================================
> OpenSearch Build Hamster says Hello!
>   Gradle Version        : 7.4.2
>   OS Info               : Mac OS X 13.2 (x86_64)
>   JDK Version           : 11 (Amazon Corretto JDK)
>   JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
>   Random Testing Seed   : 32B6B964AEB93F20
>   In FIPS 140 mode      : false
> =======================================
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD SUCCESSFUL in 2s
> 10 actionable tasks: 3 executed, 7 up-to-date
> maharup@b0f1d879dff7 observability % find snapshots | sort                                     
> snapshots
> snapshots/org
> snapshots/org/opensearch
> snapshots/org/opensearch/plugin
> snapshots/org/opensearch/plugin/observability
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.md5
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.sha1
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.sha256
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.pom.sha512
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.md5
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.sha1
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.sha256
> snapshots/org/opensearch/plugin/observability/3.0.0.0-SNAPSHOT/observability-3.0.0.0-20230221.024948-1.zip.sha512
> snapshots/org/opensearch/plugin/observability/maven-metadata.xml
> snapshots/org/opensearch/plugin/observability/maven-metadata.xml.md5
> snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha1
> snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha256
> snapshots/org/opensearch/plugin/observability/maven-metadata.xml.sha512
> snapshots/org/opensearch/plugin/opensearch-observability
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.md5
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.sha1
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.sha256
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.pom.sha512
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.md5
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.sha1
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.sha256
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.025800-1.zip.sha512
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.md5
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.sha1
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.sha256
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.pom.sha512
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.md5
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.sha1
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.sha256
> snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.171629-2.zip.sha512
> snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml
> snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.md5
> snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha1
> snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha256
> snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha512
> maharup@b0f1d879dff7 observability % 
> ```


Hey! Looks like it is still publishing observability as well as opensearch-observability? Can you recheck? Not sure if these were previous artifacts. Make clean the directory and then republish?
Thanks!

**Comment by rupal-bq** [comment]
> Hey! Looks like it is still publishing observability as well as opensearch-observability? Can you recheck? Not sure if these were previous artifacts. Make clean the directory and then republish? Thanks!

Sorry, I forgot to clear the directory. Output with clean directory
```
maharup@b0f1d879dff7 observability % ./gradlew publishPluginZipPublicationToSnapshotsRepository                                                  
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 13.2 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
  Random Testing Seed   : B61715B95E9185B3
  In FIPS 140 mode      : false
=======================================

> Task :compileKotlin
w: /Users/maharup/GitRepoWorkspace/observability/src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt: (95, 18): 'mapping(String!, XContentType!): CreateIndexRequest!' is deprecated. Deprecated in Java
w: /Users/maharup/GitRepoWorkspace/observability/src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt: (96, 18): 'settings(String!, XContentType!): CreateIndexRequest!' is deprecated. Deprecated in Java
w: /Users/maharup/GitRepoWorkspace/observability/src/main/kotlin/org/opensearch/observability/metrics/RollingCounter.kt: (36, 13): Parameter 'k' is never used, could be renamed to _

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 51s
10 actionable tasks: 10 executed
maharup@b0f1d879dff7 observability % find snapshots | sort                                                                                       
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/opensearch-observability
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.pom
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.pom.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.pom.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.pom.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.pom.sha512
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.zip
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.zip.md5
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.zip.sha1
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.zip.sha256
snapshots/org/opensearch/plugin/opensearch-observability/3.0.0.0-SNAPSHOT/opensearch-observability-3.0.0.0-20230221.181442-1.zip.sha512
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-observability/maven-metadata.xml.sha512
```

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Added the secret role. You are good to merge.
Thanks!

**Comment by prudhvigodithi** [comment]
Hey to avoid confusion in future, please add `settings.gradle`  file with `rootProject.name = 'opensearch-observability'`
Example https://github.com/opensearch-project/job-scheduler/blob/main/settings.gradle#L6
@rupal-bq @ps48 @derek-ho

**Review by YANG-DB — APPROVED** [review]

**Comment by gaiksaya** [comment]
Looks like the workflow is failing @rupal-bq https://github.com/opensearch-project/observability/actions/runs/4236736463/jobs/7361884843
Can you take a look and fix it?
Thanks!

**Comment by rupal-bq** [comment]
> Looks like the workflow is failing @rupal-bq https://github.com/opensearch-project/observability/actions/runs/4236736463/jobs/7361884843 Can you take a look and fix it? Thanks!

I think it's failing because job-scheduler is missing. I see job scheduler [PR](https://github.com/opensearch-project/job-scheduler/pull/320) isn't merged yet. Reporting also has same error and depends on job-scheduler.
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.opensearch.jobscheduler.spi.ScheduledJobParameter, unresolved supertypes: org.opensearch.common.xcontent.ToXContentObject
    class org.opensearch.commons.authuser.User, unresolved supertypes: org.opensearch.common.xcontent.ToXContent
    class org.opensearch.jobscheduler.spi.schedule.Schedule, unresolved supertypes: org.opensearch.common.xcontent.ToXContentObject
Adding -Xextended-compiler-checks argument might provide additional information.
```

**Comment by gaiksaya** [comment]
I think this is the PR that needs to go in https://github.com/opensearch-project/job-scheduler/pull/321

**Pull request merged**
