### PR TITLE
Updates sample cert and admin keystore

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Downstream change coming from security plugin: https://github.com/opensearch-project/security/pull/4061

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
should be merged post https://github.com/opensearch-project/security/pull/4061 is merged

**Review by derek-ho — CHANGES_REQUESTED** [review]
@DarshitChanpura can you leave some comments as to why this change is needed? Is CI failing somewhere? Can you provide a mechanism to pull these in via security plugin? I have seen you made PRs in all repos before and it feels like its better to pull it from one place and not hard code them everywhere

**Comment by DarshitChanpura** [comment]
> Can you provide a mechanism to pull these in via security plugin?

This is left onto maintainers to refactor build.gradle to pull artifacts from security repository. Refer to k-NN's [build.gradle](https://github.com/opensearch-project/k-NN/blob/main/build.gradle#L105).

Without this change, the CI will start failing since the public certificates used are updated, thus sample.pem will not be verifiable since it has old certs

**Review by derek-ho — COMMENTED** [review]
Removing the block but not approving until upstream change is merged and CI is green

**Review by derek-ho — APPROVED** [review]

**Review by derek-ho — COMMENTED** [review]
Thanks

**Comment by gaiksaya** [comment]
Hello reviewers,

This could be potential reason for failing tests with security atleast at the distribution level for 2.13.0.
Please review and merge. 

Thanks!

**Review by ps48 — APPROVED** [review]

**Pull request merged**
