### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/observability/pull/1

### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/observability/issues/834

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — DISMISSED** [review]
thanks

**Comment by prudhvigodithi** [comment]
Referred old version increment PR:
https://github.com/opensearch-project/observability/pull/785

**Review by kavithacm — DISMISSED** [review]

**Comment by prudhvigodithi** [comment]
Renaming to task updateVersion following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by prudhvigodithi** [comment]
Hey @anirudha @joshuali925 can you please take a look.
Thank you

**Review by joshuali925 — APPROVED** [review]

**Review by kavithacm — APPROVED** [review]

**Pull request merged**
