### PR TITLE
Remove runtime antlr - ( workaround for 2.4 release. - we need to revert this )

### PR DESCRIPTION
**Pull request by mengweieric**
### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by sejli — APPROVED** [review]

**Review by ps48 — APPROVED** [review]

**Comment by dblock** [comment]
This is a fine workaround, but how are you going to keep it in sync? I think you need something (a test in CI?) that ensures build fails if these files are out of sync.

**Comment by CEHENKLE** [comment]
To second what dB said -- this will unblock us but it's incredibly fragile.  Please open an issue to track a long term solution and link it here before merge.

**Comment by mengweieric** [comment]
> This is a fine workaround, but how are you going to keep it in sync? I think you need something (a test in CI?) that ensures build fails if these files are out of sync.

It currently has no way to keep files in sync yet, the files are just manually generated locally for a specific version of the grammar files. But yes to your point we may need such tests to check if these files are in sync. Previously we were just making it generate grammar files on every builds.

**Comment by dblock** [comment]
> > This is a fine workaround, but how are you going to keep it in sync? I think you need something (a test in CI?) that ensures build fails if these files are out of sync.
> 
> It currently has no way to keep files in sync yet, the files are just manually generated locally for a specific version of the grammar files. But yes to your point we may need such tests to check if these files are in sync. Previously we were just making it generate grammar files on every builds.

I suggest doing two things:

1. In this PR, generate these files, and fail the CI if any of these files have changed (e.g. with https://github.com/marketplace/actions/changed-files)
2. Open an issue to remove the generated files linking to why we implemented this.

**Pull request merged**
