### PR TITLE
updated workflows and version to 3.0.0

### LINKED ISSUE #869: Implement OpenSearch core branching strategy
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

### PR DESCRIPTION
**Pull request by ps48**
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>

### Description
updated workflows and version to 3.0.0

### Issues Resolved
#869 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kavithacm — APPROVED** [review]

**Comment by ps48** [comment]
Backend plugin fails due to [missing Job Scheduler artifact](https://github.com/opensearch-project/job-scheduler/issues/205)

**Comment by anirudha** [comment]
closing older test PR with conflict.

**Comment by ps48** [comment]
Bwc tests fail here, related to: https://github.com/opensearch-project/job-scheduler/pull/242

**Comment by ps48** [comment]
Waiting for 2.4.0 dist. build to successful on OS side.

**Comment by ps48** [comment]
Seeing this error during bwc testing:
```
> Task :compileTestKotlin FAILED
e: /home/ubuntu/check_ci/observability/opensearch-observability/src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt: (9, 19): Unresolved reference: http
e: /home/ubuntu/check_ci/observability/opensearch-observability/src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt: (63, 83): Unresolved reference: value
e: /home/ubuntu/check_ci/observability/opensearch-observability/src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt: (100, 63): Unresolved reference: HttpHost
e: /home/ubuntu/check_ci/observability/opensearch-observability/src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt: (118, 38): Overload resolution ambiguity:
public open fun builder(vararg p0: HttpHost!): RestClientBuilder! defined in org.opensearch.client.RestClient
public open fun builder(vararg p0: Node!): RestClientBuilder! defined in org.opensearch.client.RestClient

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestKotlin'.
> Compilation error. See log for more details
```

**Review by kavithacm — APPROVED** [review]

**Review by joshuali925 — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]

**Pull request merged**
